title: Michael Owoicho Ogaje — Resume
profile_img: /assets/img/profile.webp  # Make sure this image exists
icon_img: /assets/img/icon.webp        # Favicon/icon image

name: "Michael Owoicho Ogaje"
job: "Python Developer • AI Automation Engineer"

phone_number: 08142878380
address: Abuja, Nigeria
email: michaelogaje033@gmail.com

linkedin_username: michael-ogaje-3a8323377
github_username: owoicho09
twitter_username:  # No Twitter
instagram_username: kacheofficiall
facebook_username:  # No Facebook
youtube_username:   # No YouTube
blog_url: https://owoicho09.github.io/seo-blog/

# If your repo name follows the format "<username>.github.io", leave this blank
baseurl: 

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
